modLoader = "javafml"
loaderVersion = "[39,)"
issueTrackerURL = "https://github.com/MoonflowerTeam/${repo}/issues"
license = "GPLv3"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Moonflower"
credits = "An author, another author, and the last author."
description = '''
Make creepers no longer grief unjustly, but make them more of an interesting enemy: they spawn creepies now!
'''
#updateJSONURL = ""
#logoFile = ""

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "pollen"
mandatory = true
versionRange = "[1.5.0,)"
ordering = "BEFORE"
side = "BOTH"