modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/MoonflowerTeam/starter/issues"
license = "GPLv3"

[[mods]]
modId = "starter"
version = "${version}"
displayName = "Starter"
authors = "Moonflower Studio"
credits = "An author, another author, and the last author."
description = '''
This is an example starter template.
'''
updateJSONURL = "https://github.com/MoonflowerTeam/starter/update.json"
#logoFile = ""

[[dependencies.starter]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.starter]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17,)"
ordering = "NONE"
side = "BOTH"